name = "hakusan-badge-quest"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "hakusan-badge-quest"
database_id = "8bb891f4-915e-41dd-99f9-7988cc684689"
